version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    open-telemetry:
      patterns:
        - "*opentelemetry*"
    pylint:
      patterns:
        - "*pylint*"
        - "*astroid*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10